# main.py (Streamlit Example)
import pandas as pd
import streamlit as st

st.title("🇲🇾 Malaysian Data Analyst Job Market Tracker")
st.write("Data updated automatically every night via GitHub Actions.")

try:
    # Read the data file pushed by your GitHub Action
    df = pd.read_json("linkedin_jobs.jsonl", lines=True)

    # Display an interactive table
    st.subheader("Latest Job Openings")
    st.dataframe(df[["title", "company", "location", "date_scraped"]])

except FileNotFoundError:
    st.warning("Data file is being generated by the automation worker. Check back shortly!")